language: julia

julia:
  - 1.0
  - 1.1
  - nightly

notifications:
  email: false

matrix:
  allow_failures:
    - julia: nightly

addons:
  apt:
    packages:
      - libcfitsio3

jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
